on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Run git config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "tnc1997@virginmedia.com"
          git config --global user.name "Thomas Clark"
          git remote set-url origin https://tnc1997:"$GITHUB_TOKEN"@github.com/tnc1997/ts-utils.git
      - name: Run rush install
        run: node ./common/scripts/install-run-rush.js install
      - name: Run rush rebuild
        run: node ./common/scripts/install-run-rush.js rebuild --verbose
      - name: Run rush publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: node ./common/scripts/install-run-rush.js publish --apply --target-branch "master" --publish --npm-auth-token "$NPM_AUTH_TOKEN" --set-access-level "public"
